---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ld7wz23lmtc4/public_html/
    - /bin/cp -R component $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.ssl.txt $DEPLOYPATH